
service: d365-integ # NOTE: update this with your service name

custom:
  global:
    bucketName:
      Fn::Join:
      - ''
      - - 'existings3-bug-'
        - ${self:provider.stage}
        - Ref: AWS::AccountId

provider:
  name: aws
  runtime: java8

# you can overwrite defaults here
  stage: dev
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "s3:*"
      - "s3:PutObject"
      - "s3:DeleteObject"
      - "s3:GetObjectTagging"
      - "s3:PutObjectTaggings"
      - "s3:PutBucketNotification"
      Resource: "arn:aws:s3:::*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
    - existingS3:
        bucket: ${self:custom.global.bucketName}
        events:
        - s3:ObjectCreated:*    

resources:
  Resources:
    VendorBucketName:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.global.bucketName}

plugins:
  - serverless-plugin-existing-s3
  - serverless-pseudo-parameters
